<body class="cssbody"><!--credit to lucas for the header-->
    <header>
        <div class="header-flex">
            <img src="images/logoupdate.png" alt="Logo" class="logo">
            <div class="center-container">
                <h1 class="typewriter">Optional Programmers</h1>
            </div>
        </div>


        <nav>
            <a href="about.html"><img src="images/user.png" width="18" height="18" alt="User Icon"> About us</a>
            <a href="jobs.html"><img src="images/briefcase.png" width="18" height="18" alt="Job Icon"> Job Description</a>
            <a href="index.html"><img src="images/home.png" width="18" height="18" alt="Home Icon"> Index</a>
            <a href="apply.html"><img src="images/edit.png" width="18" height="18" alt="Apply Icon"> Apply</a>
        </nav>
        <hr class="hr">
    </header>