<nav>
            <a href="project2/about.php"><img src="images/user.png" width="18" height="18" alt="User Icon"> About us</a>
            <a href="project2/jobs.php"><img src="images/briefcase.png" width="18" height="18" alt="Job Icon"> Job Description</a>
            <a href="project2/index.php"><img src="images/home.png" width="18" height="18" alt="Home Icon"> Index</a>
            <a href="project2/apply.php"><img src="images/edit.png" width="18" height="18" alt="Apply Icon"> Apply</a>
        </nav>