    <footer class="indexfooter">
        <p>
            If you have any further questions<br>
            please contact us at <a href="info@OptionalProgrammers.com.au">info@OptionalProgrammers.com.au</a>
        </p>
        <P>
            <a href="https://lucasjurgec.atlassian.net/jira/software/projects/WTP1/boards/68">Jira</a> <a
                href="https://github.com/TwentyTwoCharacters/Web-Tech-Project-1">Github</a>
        </P>

        <p>
        <a href=".\staff\staff_login.php"> Staff Login </a>
    </footer>

</body>
