<body class="cssbody">
    <header>
        <div class="header-flex">
            <a href="index.php">
            <img src="../images/logoupdate.jpg" alt="Logo" class="logo">
            </a>
            <div class="center-container">
                <h1 class="typewriter">Optional Programmers</h1>
            </div>
        </div>

        <?php include '../nav.inc';?>
 
        <hr class="hr">
    </header>